### ISSUE TITLE
css support?

### ISSUE THREAD

**Issue by jimimaher** [GAumala/gulp-prettier-plugin#4]
Errors out when attempting formatting a Less file. Ever consider adding Less/SCSS support to this plugin? Would be great if it could be handled with this plugin instead of another one specific to styles.

**Comment by GAumala** [comment]
CSS should definitely be supported. I haven't tested it because I haven't been working with CSS recently, but I'll try to figure out what is going on.

**Comment by GAumala** [comment]
I just release version `1.1.0` Which now correctly infers the parser using the file's name. This should support CSS and other file types correctly without any extra configuration. Please upgrade and see if it solves your issue.
